# Generated by Django 2.1.5 on 2019-01-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(upload_to='portafolio', verbose_name='Imagen'),
        ),
    ]
