# Generated by Django 2.1.5 on 2019-01-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190119_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='image',
            field=models.ImageField(blank=True, default=True, upload_to='portafolio', verbose_name='Imagen'),
        ),
    ]
