# Generated by Django 2.1.5 on 2019-01-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190120_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portafolio',
            name='image',
        ),
    ]
