# Generated by Django 2.1.5 on 2019-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190121_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
